import Head from 'next/head';
import Image from 'next/image';
import React, { useEffect, useState } from 'react';
import Cards from '../components/Cards/Cards';
import styles from '../styles/Home.module.css';
import { LaunchResponseData } from '../types/types'
import { fetchSpaceXLaunchData } from '../utils/apiUtils';


export default function Home() {
  const [launchData, setLaunchData] = useState<LaunchResponseData[]>([])

  useEffect(() => {
    const fetchApi = async () => {
      const resolvedValue = await fetchSpaceXLaunchData()
      setLaunchData(resolvedValue?.data?.docs)
    }

    fetchApi()
  }, [])


  return (
    <div data-testid='wrapper' className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.titleContainer}>
          <h1 className={styles.title}>
            Welcome to SpaceX Launches
          </h1>
        </div>

        <p className={styles.description}>
          Page dedicated to information on the latest launches from SpaceX
        </p>

        <div className={styles.grid}>
          {Array.isArray(launchData) && launchData.map(launch => {
            const { name, date_utc, cores, payloads, success, failures, links, id } = launch
            return (
              <Cards
                key={id}
                name={name}
                date_utc={date_utc}
                cores={cores}
                payloads={payloads}
                success={success}
                failures={failures}
                links={links}
              />
            )
          })
          }

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div >
  );
}
